### ISSUE TITLE
Error building examples

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-draw#190]
`sh build-examples.sh` yields:
```bash
SyntaxError: /home/mapbox-gl-draw/examples/geojson-editor/index.js: Unexpected token (77:6)
  75 |     var input = this.state.input;
  76 |     return (
> 77 |       <div className='side-bar'>
     |       ^
  78 |
  79 |         <fieldset className='with-icon dark'>
  80 |           <span className='icon search'></span>
    at Parser.pp.raise (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:2907:8)
    at Parser.pp.parseExprAtom (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:754:12)
    at Parser.pp.parseExprSubscripts (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:509:19)
    at Parser.pp.parseMaybeUnary (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:489:19)
    at Parser.pp.parseExprOps (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:420:19)
    at Parser.pp.parseMaybeConditional (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:402:19)
    at Parser.pp.parseMaybeAssign (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:365:19)
    at Parser.pp.parseParenAndDistinguishExpression (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:827:26)
    at Parser.pp.parseExprAtom (/home/mapbox-gl-draw/node_modules/babelify/node_modules/babel-core/node_modules/babylon/index.js:713:19)

```

On both master and `v0.1.6` tag.

**Comment by mcwhittemore** [comment]
Our examples are extremely out of date and don't have a clear "this is demoing this" structure. Currently debug/index.html is the best working "example", though I'd like to see it have better api coverage and use the console less.

Personally I think we should drop the current examples and create a few tickets for examples we'd like to see on a future mb-pages branch. mb-pages will be published on mapbox.com and will start to let us support a CDN as well (#189).

/cc @kelvinabrokwa @lucaswoj

**Comment by lucaswoj** [comment]
I think a super simple "this is mapbox-gl-draw, here's a functioning instance to play with, here's the code to create it" page, a la the [Turf.js page](http://turfjs.org/) would be a great place to start.

**Comment by mcwhittemore** [comment]
@lucaswoj I agree. The debug page is effectively this for us until we get mb-pages up and running. I don't see the examples making the move to mb-pages as they are now, so maybe we should drop them.

**Comment by kelvinabrokwa** [comment]
@mcwhittemore I say drop them -> https://github.com/mapbox/mapbox-gl-draw/pull/221

**Comment by kelvinabrokwa** [comment]
the examples have been dropped
